version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini
        ports:
            - '80:80'
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: '${DB_DATABASE:-laravel}'
            DB_USERNAME: '${DB_USERNAME:-laravel}'
            DB_PASSWORD: '${DB_PASSWORD:-password}'
        depends_on:
            - postgres
        networks:
            - laravel

    postgres:
        image: postgres:13
        container_name: laravel-postgres
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-laravel}'
            POSTGRES_USER: '${DB_USERNAME:-laravel}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - laravel-postgres-data:/var/lib/postgresql/data
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel}"]
            retries: 3
            timeout: 5s

networks:
    laravel:
        driver: bridge

volumes:
    laravel-postgres-data:
        driver: local
